FROM registry.connect.redhat.com/intel/openvino-runtime
#WORKDIR /app
#COPY requirements.txt /app
#RUN pip3 install -r requirements.txt --no-cache-dir
#COPY . /app
#ENTRYPOINT ["python3"]
#CMD ["app.py"]
RUN mkdir mangal-dock
